# tests/run_tests.mojo — single-binary test runner. Each test is a `def` that
# raises on failure; `main` runs every test in an explicit try/except block
# and reports PASS/FAIL. Explicit blocks are a probed decision, not a habit:
# named functions do not coerce to function-type parameters in this toolchain
# (.probe/SYNTAX.md, finding 8).

from color import Painter as PublicPainter
from color import strip_escapes as public_strip_escapes
from color._internal.decimal import DIGIT_PAIRS, write_decimal
from color._internal.quantize import ansi256_to_named16, rgb_to_ansi256
from color._internal.sgr import (
    ATTRIBUTE_CODES,
    RESET_SEQUENCE,
    is_csi_final,
    is_csi_intermediate,
    is_csi_parameter,
)
from color.attribute import Attribute
from color.color import Color
from color.color_level import ColorLevel, _is_forcing
from color.painter import Painter
from color.style import Style
from color.visible import strip_escapes, visible_width


def _assert(condition: Bool, message: String) raises:
    if not condition:
        raise Error("assertion failed: " + message)


# --- _internal/sgr -----------------------------------------------------------


def test_sgr_attribute_codes_skip_six() raises:
    _assert(ATTRIBUTE_CODES == "12345789", "codes 1..9 without 6")
    _assert(RESET_SEQUENCE == "\x1b[0m", "reset sequence")


def test_sgr_byte_classes_match_ecma48() raises:
    _assert(not is_csi_final(UInt8(0x3F)), "0x3F below final range")
    _assert(is_csi_final(UInt8(0x40)), "0x40 opens final range")
    _assert(is_csi_final(UInt8(0x6D)), "'m' is a final byte")
    _assert(is_csi_final(UInt8(0x7E)), "0x7E closes final range")
    _assert(not is_csi_final(UInt8(0x7F)), "0x7F above final range")
    _assert(is_csi_parameter(UInt8(ord("0"))), "digits are parameter bytes")
    _assert(is_csi_parameter(UInt8(ord(";"))), "semicolon is a parameter byte")
    _assert(is_csi_intermediate(UInt8(0x20)), "space opens intermediates")
    _assert(not is_csi_intermediate(UInt8(0x30)), "0x30 is not intermediate")


# --- _internal/decimal -------------------------------------------------------


def test_write_decimal_fills_exactly() raises:
    var buffer = InlineArray[UInt8, 8](uninitialized=True)
    var offset = write_decimal(buffer, 0, 0)
    offset = write_decimal(buffer, offset, 42)
    offset = write_decimal(buffer, offset, 108)
    _assert(offset == 6, "offsets advance by digit count")
    var text = StringSlice(unsafe_from_utf8=Span(buffer)[0:offset])
    _assert(text == "042108", "digits placed exactly")


def test_digit_pairs_spot_checks() raises:
    var table = DIGIT_PAIRS.as_bytes()
    _assert(table[0] == UInt8(ord("0")), "pair 00 high digit")
    _assert(table[1] == UInt8(ord("0")), "pair 00 low digit")
    _assert(table[2 * 37] == UInt8(ord("3")), "pair 37 high digit")
    _assert(table[2 * 37 + 1] == UInt8(ord("7")), "pair 37 low digit")
    _assert(table[2 * 99 + 1] == UInt8(ord("9")), "pair 99 low digit")


# --- _internal/quantize ------------------------------------------------------
#
# Expected values generated by .probe/quantize_reference.py — differential
# vectors, not hand-derived.


def test_rgb_to_ansi256_reference_vectors() raises:
    _assert(rgb_to_ansi256(255, 0, 0) == UInt8(196), "pure red -> 196")
    _assert(rgb_to_ansi256(0, 255, 0) == UInt8(46), "pure green -> 46")
    _assert(rgb_to_ansi256(0, 0, 255) == UInt8(21), "pure blue -> 21")
    _assert(rgb_to_ansi256(255, 255, 255) == UInt8(231), "white -> 231")
    _assert(rgb_to_ansi256(0, 0, 0) == UInt8(16), "black -> 16")
    _assert(rgb_to_ansi256(255, 100, 0) == UInt8(202), "orange -> 202")
    _assert(rgb_to_ansi256(0, 128, 128) == UInt8(30), "teal -> 30")
    _assert(rgb_to_ansi256(128, 128, 128) == UInt8(244), "mid gray -> ramp 244")
    _assert(rgb_to_ansi256(250, 250, 250) == UInt8(231), "near white -> 231")
    _assert(rgb_to_ansi256(8, 8, 8) == UInt8(232), "darkest ramp gray -> 232")
    _assert(rgb_to_ansi256(1, 1, 1) == UInt8(16), "near black -> cube 16")
    _assert(rgb_to_ansi256(95, 135, 175) == UInt8(67), "slate -> 67")
    _assert(rgb_to_ansi256(255, 215, 0) == UInt8(220), "gold -> 220")
    _assert(rgb_to_ansi256(46, 52, 64) == UInt8(237), "dark slate -> ramp 237")


def test_ansi256_to_named16_reference_vectors() raises:
    _assert(ansi256_to_named16(UInt8(196)) == UInt8(9), "196 -> bright red")
    _assert(ansi256_to_named16(UInt8(46)) == UInt8(10), "46 -> bright green")
    _assert(ansi256_to_named16(UInt8(21)) == UInt8(4), "21 -> blue")
    _assert(ansi256_to_named16(UInt8(231)) == UInt8(15), "231 -> bright white")
    _assert(ansi256_to_named16(UInt8(16)) == UInt8(0), "16 -> black")
    _assert(ansi256_to_named16(UInt8(202)) == UInt8(9), "202 -> bright red")
    _assert(ansi256_to_named16(UInt8(30)) == UInt8(6), "30 -> cyan")
    _assert(ansi256_to_named16(UInt8(244)) == UInt8(8), "244 -> bright black")
    _assert(ansi256_to_named16(UInt8(220)) == UInt8(11), "220 -> bright yellow")
    _assert(ansi256_to_named16(UInt8(237)) == UInt8(0), "237 -> black")
    _assert(ansi256_to_named16(UInt8(7)) == UInt8(7), "below 16 is identity")


# --- color_level -------------------------------------------------------------
#
# Resolution is a pure function: every case passes its complete signal set
# explicitly (an empty string reads as unset) and nothing touches the process
# environment, so cases cannot interact. The TTY gate is testable directly —
# an environment-probing design never allowed that under a piped runner.


def test_color_level_ordering() raises:
    _assert(ColorLevel.TRUECOLOR > ColorLevel.ANSI256, "truecolor above 256")
    _assert(ColorLevel.ANSI256 > ColorLevel.ANSI16, "256 above 16")
    _assert(ColorLevel.ANSI16 > ColorLevel.NONE, "16 above none")
    _assert(ColorLevel.NONE == ColorLevel.NONE, "equality")
    _assert(not ColorLevel.NONE.is_enabled(), "NONE is disabled")
    _assert(ColorLevel.ANSI16.is_enabled(), "ANSI16 is enabled")


def test_resolve_no_color_always_wins() raises:
    _assert(
        ColorLevel.resolve(
            is_tty=True,
            no_color="1",
            force_color="1",
            colorterm="truecolor",
            term="xterm",
        )
        == ColorLevel.NONE,
        "no_color beats everything",
    )


def test_resolve_tty_gate() raises:
    _assert(
        ColorLevel.resolve(is_tty=True, term="xterm") == ColorLevel.ANSI16,
        "a TTY with a plain terminal name gets ANSI16",
    )
    _assert(
        ColorLevel.resolve(is_tty=False, term="xterm") == ColorLevel.NONE,
        "a non-TTY destination stays plain",
    )
    _assert(
        ColorLevel.resolve(is_tty=True) == ColorLevel.NONE,
        "a TTY with no terminal identity stays plain",
    )
    _assert(
        ColorLevel.resolve(is_tty=True, term="xterm-256color")
        == ColorLevel.ANSI256,
        "a TTY announcing 256color gets ANSI256",
    )


def test_resolve_forced_ladder() raises:
    # is_tty=False throughout: a force flag must skip the TTY gate.
    _assert(
        ColorLevel.resolve(
            is_tty=False,
            force_color="1",
            colorterm="truecolor",
            term="xterm",
        )
        == ColorLevel.TRUECOLOR,
        "colorterm truecolor",
    )
    _assert(
        ColorLevel.resolve(
            is_tty=False, force_color="1", colorterm="24bit", term="xterm"
        )
        == ColorLevel.TRUECOLOR,
        "colorterm 24bit",
    )
    _assert(
        ColorLevel.resolve(is_tty=False, force_color="1", term="xterm-256color")
        == ColorLevel.ANSI256,
        "term 256color suffix",
    )
    _assert(
        ColorLevel.resolve(is_tty=False, force_color="1", term="dumb")
        == ColorLevel.NONE,
        "dumb cannot be forced",
    )
    _assert(
        ColorLevel.resolve(is_tty=False, force_color="1", term="xterm")
        == ColorLevel.ANSI16,
        "plain terminal name",
    )
    _assert(
        ColorLevel.resolve(is_tty=False, force_color="1") == ColorLevel.ANSI16,
        "forced with no term",
    )


def test_resolve_zero_never_forces() raises:
    _assert(not _is_forcing("0"), "the conventional off value never forces")
    _assert(not _is_forcing(""), "unset never forces")
    _assert(_is_forcing("1"), "any other value forces")
    _assert(_is_forcing("true"), "any other value forces")

    # force_color="0" is the convention's explicit disable — NONE before
    # the TTY gate is even consulted.
    _assert(
        ColorLevel.resolve(
            is_tty=True,
            force_color="0",
            colorterm="truecolor",
            term="xterm",
        )
        == ColorLevel.NONE,
        "force_color=0 disables",
    )


def test_resolve_dumb_outranks_colorterm() raises:
    _assert(
        ColorLevel.resolve(
            is_tty=True,
            force_color="1",
            colorterm="truecolor",
            term="dumb",
        )
        == ColorLevel.NONE,
        "an inherited colorterm cannot rescue a dumb terminal",
    )


def test_resolve_clicolor_zero_disables() raises:
    _assert(
        ColorLevel.resolve(
            is_tty=True,
            clicolor="0",
            colorterm="truecolor",
            term="xterm",
        )
        == ColorLevel.NONE,
        "clicolor=0 disables when nothing forces",
    )
    _assert(
        ColorLevel.resolve(
            is_tty=True,
            clicolor="0",
            clicolor_force="1",
            colorterm="truecolor",
            term="xterm",
        )
        == ColorLevel.TRUECOLOR,
        "a force flag outranks clicolor=0",
    )


def test_resolve_force_color_false_disables() raises:
    _assert(
        ColorLevel.resolve(
            is_tty=True,
            force_color="false",
            clicolor_force="1",
            colorterm="truecolor",
            term="xterm",
        )
        == ColorLevel.NONE,
        "force_color=false disables, even against another force flag",
    )


def test_resolve_force_color_numeric_floors() raises:
    _assert(
        ColorLevel.resolve(is_tty=False, force_color="2") == ColorLevel.ANSI256,
        "2 floors 256, no term",
    )
    _assert(
        ColorLevel.resolve(is_tty=False, force_color="2", term="xterm")
        == ColorLevel.ANSI256,
        "2 outranks a plain term",
    )
    _assert(
        ColorLevel.resolve(is_tty=False, force_color="3", term="xterm")
        == ColorLevel.TRUECOLOR,
        "3 floors truecolor",
    )
    _assert(
        ColorLevel.resolve(is_tty=False, force_color="3", term="dumb")
        == ColorLevel.NONE,
        "dumb outranks numeric force",
    )
    _assert(
        ColorLevel.resolve(
            is_tty=False,
            force_color="2",
            colorterm="truecolor",
            term="xterm",
        )
        == ColorLevel.TRUECOLOR,
        "a floor is never a ceiling — colorterm still wins",
    )
    _assert(
        ColorLevel.resolve(is_tty=False, force_color="1", term="xterm-256color")
        == ColorLevel.ANSI256,
        "announcements above the floor still count",
    )


# --- attribute ---------------------------------------------------------------


def test_attribute_bits_are_distinct() raises:
    _assert(Attribute.BOLD.bits() == UInt8(1), "bold is bit 0")
    _assert(Attribute.DIM.bits() == UInt8(2), "dim is bit 1")
    _assert(Attribute.ITALIC.bits() == UInt8(4), "italic is bit 2")
    _assert(Attribute.UNDERLINE.bits() == UInt8(8), "underline is bit 3")
    _assert(Attribute.BLINK.bits() == UInt8(16), "blink is bit 4")
    _assert(Attribute.REVERSE.bits() == UInt8(32), "reverse is bit 5")
    _assert(Attribute.HIDDEN.bits() == UInt8(64), "hidden is bit 6")
    _assert(
        Attribute.STRIKETHROUGH.bits() == UInt8(128), "strikethrough is bit 7"
    )


def test_attribute_combination() raises:
    var combined = Attribute.BOLD | Attribute.ITALIC
    _assert(combined.contains(Attribute.BOLD), "contains bold")
    _assert(combined.contains(Attribute.ITALIC), "contains italic")
    _assert(not combined.contains(Attribute.UNDERLINE), "no underline")
    _assert(not combined.is_empty(), "combined set is not empty")
    _assert(Attribute.NONE.is_empty(), "NONE is empty")
    _assert(
        (combined & Attribute.BOLD) == Attribute.BOLD, "intersection keeps bold"
    )
    _assert(
        combined == (Attribute.ITALIC | Attribute.BOLD), "order-insensitive"
    )


# --- color -------------------------------------------------------------------


def test_color_constants_store_palette_indexes() raises:
    _assert(Color.BLACK == Color._named(UInt8(0)), "BLACK is index 0")
    _assert(Color.RED == Color._named(UInt8(1)), "RED is index 1")
    _assert(Color.WHITE == Color._named(UInt8(7)), "WHITE is index 7")
    _assert(Color.BRIGHT_BLACK == Color._named(UInt8(8)), "BRIGHT_BLACK is 8")
    _assert(Color.BRIGHT_WHITE == Color._named(UInt8(15)), "BRIGHT_WHITE is 15")
    _assert(Color.RED != Color.BLACK, "distinct constants differ")


def test_color_value_equality() raises:
    var orange = Color.rgb(red=255, green=100, blue=0)
    _assert(orange == Color.rgb(red=255, green=100, blue=0), "same rgb equal")
    _assert(orange != Color.rgb(red=255, green=100, blue=1), "one channel off")
    _assert(Color.ansi256(196) == Color.ansi256(196), "same index equal")
    _assert(Color.ansi256(1) != Color.RED, "kinds keep values distinct")


def test_color_from_hex_parses_forms() raises:
    var orange = Color.rgb(red=255, green=100, blue=0)
    _assert(Color.from_hex("#ff6400") == orange, "lowercase with hash")
    _assert(Color.from_hex("FF6400") == orange, "uppercase without hash")
    _assert(
        Color.from_hex("#000000") == Color.rgb(red=0, green=0, blue=0),
        "black parses",
    )


def test_color_from_hex_rejects_malformed() raises:
    var rejected = 0
    try:
        _ = Color.from_hex("#ff640")  # five digits
    except error:
        rejected += 1
        _assert(
            String(error).find("color.Color") >= 0, "error names the module"
        )
    try:
        _ = Color.from_hex("zzzzzz")
    except error:
        rejected += 1
    try:
        _ = Color.from_hex("")
    except error:
        rejected += 1
    _assert(rejected == 3, "all malformed inputs rejected")


def test_color_downgrade_walks_the_ladder() raises:
    var red = Color.rgb(red=255, green=0, blue=0)
    _assert(
        red.downgrade_to(ColorLevel.ANSI256) == Color.ansi256(196),
        "rgb red to palette 196",
    )
    _assert(
        red.downgrade_to(ColorLevel.ANSI16) == Color.BRIGHT_RED,
        "rgb red to bright red",
    )
    _assert(
        Color.ansi256(244).downgrade_to(ColorLevel.ANSI16)
        == Color.BRIGHT_BLACK,
        "palette gray to bright black",
    )
    _assert(
        red.downgrade_to(ColorLevel.TRUECOLOR) == red, "truecolor is identity"
    )
    _assert(red.downgrade_to(ColorLevel.NONE) == red, "NONE is identity")
    _assert(
        Color.CYAN.downgrade_to(ColorLevel.ANSI16) == Color.CYAN,
        "named passes through",
    )
    _assert(
        Color.ansi256(30).downgrade_to(ColorLevel.ANSI256) == Color.ansi256(30),
        "palette at own tier passes through",
    )


# --- style -------------------------------------------------------------------


def test_style_empty_is_identity() raises:
    _assert(Style().paint("hi") == "hi", "empty style changes nothing")
    _assert(Style().is_empty(), "fresh style is empty")
    _assert(not Style().bold().is_empty(), "an attribute makes it non-empty")


def test_style_paints_named_colors() raises:
    var got = Style().foreground(Color.RED).paint("oops")
    _assert(got == "\x1b[31moops\x1b[0m", "red foreground")
    got = Style().background(Color.BLUE).paint("x")
    _assert(got == "\x1b[44mx\x1b[0m", "blue background is 34+10")
    got = Style().foreground(Color.BRIGHT_CYAN).paint("x")
    _assert(got == "\x1b[96mx\x1b[0m", "bright cyan foreground is 96")
    got = Style().background(Color.BRIGHT_RED).paint("x")
    _assert(got == "\x1b[101mx\x1b[0m", "bright red background is 101")


def test_style_paints_attributes() raises:
    var got = Style().bold().paint("y")
    _assert(got == "\x1b[1my\x1b[0m", "bold is SGR 1")
    got = (
        Style()
        .bold()
        .dim()
        .italic()
        .underline()
        .blink()
        .reverse()
        .hidden()
        .strikethrough()
        .paint("x")
    )
    _assert(got == "\x1b[1;2;3;4;5;7;8;9mx\x1b[0m", "all eight, six skipped")


def test_style_paints_combined_parameters() raises:
    var got = (
        Style()
        .bold()
        .italic()
        .foreground(Color.YELLOW)
        .background(Color.BLACK)
        .paint("warn")
    )
    _assert(got == "\x1b[1;3;33;40mwarn\x1b[0m", "attributes then fg then bg")


def test_style_paints_extended_colors() raises:
    var got = Style().foreground(Color.ansi256(208)).paint("orange")
    _assert(got == "\x1b[38;5;208morange\x1b[0m", "256-color foreground")
    got = Style().background(Color.ansi256(8)).paint("x")
    _assert(got == "\x1b[48;5;8mx\x1b[0m", "256-color background")
    got = Style().foreground(Color.rgb(red=255, green=100, blue=0)).paint("rgb")
    _assert(got == "\x1b[38;2;255;100;0mrgb\x1b[0m", "truecolor foreground")
    got = Style().background(Color.rgb(red=0, green=0, blue=0)).paint("x")
    _assert(got == "\x1b[48;2;0;0;0mx\x1b[0m", "truecolor background zeros")


def test_style_paint_into_matches_paint() raises:
    var style = Style().bold().foreground(Color.ansi256(208))
    var sink = String("")
    style.paint_into(sink, "orange")
    _assert(sink == style.paint("orange"), "writer path emits the same bytes")

    var empty_sink = String("")
    Style().paint_into(empty_sink, "plain")
    _assert(empty_sink == "plain", "empty style streams text through")


# --- painter -----------------------------------------------------------------


def test_painter_from_level_is_deterministic() raises:
    var painter = Painter.from_level(ColorLevel.ANSI16)
    _assert(painter.red("x") == "\x1b[31mx\x1b[0m", "sugar renders red")
    _assert(painter.bold("y") == "\x1b[1my\x1b[0m", "sugar renders bold")
    _assert(
        painter.bright_cyan("z") == "\x1b[96mz\x1b[0m", "bright sugar renders"
    )
    _assert(painter.level() == ColorLevel.ANSI16, "level is stored")
    _assert(painter.is_enabled(), "ANSI16 is enabled")


def test_painter_plain_never_escapes() raises:
    var painter = Painter.plain()
    _assert(painter.red("x") == "x", "color sugar passes through")
    _assert(painter.bold("x") == "x", "attribute sugar passes through")
    var style = Style().foreground(Color.rgb(red=255, green=0, blue=0)).bold()
    _assert(painter.paint(style, "x") == "x", "full styles pass through")
    _assert(not painter.is_enabled(), "plain is disabled")


def test_painter_downgrades_through_paint() raises:
    var truecolor_red = Style().foreground(Color.rgb(red=255, green=0, blue=0))
    var at_256 = Painter.from_level(ColorLevel.ANSI256)
    _assert(
        at_256.paint(truecolor_red, "x") == "\x1b[38;5;196mx\x1b[0m",
        "rgb quantizes to palette 196",
    )
    var at_16 = Painter.from_level(ColorLevel.ANSI16)
    _assert(
        at_16.paint(truecolor_red, "x") == "\x1b[91mx\x1b[0m",
        "rgb lands on bright red",
    )
    var dark = Style().background(Color.rgb(red=0, green=0, blue=0))
    _assert(
        at_16.paint(dark, "x") == "\x1b[40mx\x1b[0m",
        "backgrounds downgrade too",
    )
    var at_truecolor = Painter.from_level(ColorLevel.TRUECOLOR)
    _assert(
        at_truecolor.paint(truecolor_red, "x") == "\x1b[38;2;255;0;0mx\x1b[0m",
        "truecolor passes through at truecolor",
    )


def test_painter_paint_into_matches_paint() raises:
    var painter = Painter.from_level(ColorLevel.ANSI256)
    var style = Style().foreground(Color.rgb(red=255, green=100, blue=0))
    var sink = String("")
    painter.paint_into(sink, style, "orange")
    _assert(sink == painter.paint(style, "orange"), "writer path matches")

    var plain_sink = String("")
    Painter.plain().paint_into(plain_sink, style, "orange")
    _assert(plain_sink == "orange", "plain painter streams text through")


def test_painter_composes_with_resolve() raises:
    # The intended wiring: the application resolves signals it gathered,
    # the Painter carries the tier — no environment access anywhere.
    var level = ColorLevel.resolve(
        is_tty=True, colorterm="truecolor", term="xterm"
    )
    var painter = Painter.from_level(level)
    _assert(painter.level() == ColorLevel.TRUECOLOR, "resolved tier carried")
    _assert(
        Painter.from_level(
            ColorLevel.resolve(is_tty=True, no_color="1", term="xterm")
        ).red("x")
        == "x",
        "a no_color resolution renders plain",
    )


# --- visible -----------------------------------------------------------------


def test_strip_escapes_removes_csi() raises:
    _assert(strip_escapes("\x1b[31mhi\x1b[0m") == "hi", "single color strips")
    _assert(
        strip_escapes("\x1b[1;3;33;40mwarn\x1b[0m") == "warn",
        "combined parameters strip",
    )
    _assert(strip_escapes("plain") == "plain", "plain text is untouched")
    _assert(strip_escapes("") == "", "empty input")


def test_strip_escapes_removes_osc_hyperlinks() raises:
    var bell_form = "\x1b]8;;http://x\x07link\x1b]8;;\x07"
    _assert(strip_escapes(bell_form) == "link", "OSC 8 with BEL terminator")
    var st_form = "\x1b]8;;u\x1b\\text\x1b]8;;\x1b\\"
    _assert(strip_escapes(st_form) == "text", "OSC 8 with ST terminator")


def test_strip_escapes_removes_plain_escape_sequences() raises:
    _assert(
        strip_escapes("\x1b(Bhello") == "hello",
        "three-byte charset shift (RFC 1468)",
    )
    _assert(strip_escapes("\x1b$@x") == "x", "another charset shift")
    _assert(strip_escapes("\x1b7save\x1b8") == "save", "two-byte sequences")


def test_strip_escapes_is_terminal_accurate_for_bare_escape() raises:
    # ESC + letter is a real two-byte sequence (ECMA-48 finals cover all
    # letters): a terminal consumes "ESC h" and shows "ello".
    _assert(strip_escapes("\x1bhello") == "ello", "ESC h is consumed")
    _assert(strip_escapes("tail\x1b") == "tail\x1b", "ESC at end stays")
    _assert(strip_escapes("\x1bé") == "\x1bé", "ESC before non-ASCII stays")


def test_visible_width_counts_code_points() raises:
    _assert(visible_width("hi") == 2, "plain ASCII")
    _assert(visible_width("") == 0, "empty")
    _assert(visible_width("\x1b[31mhi\x1b[0m") == 2, "escapes are zero width")
    _assert(visible_width("café") == 4, "multi-byte counts once")
    _assert(visible_width("🎨") == 1, "four-byte emoji counts once")
    _assert(
        visible_width("\x1b[1;31mcafé\x1b[0m") == 4,
        "styled multi-byte text",
    )
    _assert(visible_width("a\x1bb") == 1, "ESC b is a consumed sequence")
    _assert(visible_width("a\x1b") == 2, "trailing dangling ESC is one column")
    var linked = "\x1b]8;;http://x\x07link\x1b]8;;\x07"
    _assert(visible_width(linked) == 4, "hyperlink text only")


def test_visible_tools_agree_with_paint() raises:
    var painted = Style().bold().foreground(Color.ansi256(208)).paint("ALERT")
    _assert(strip_escapes(painted) == "ALERT", "strip inverts paint")
    _assert(visible_width(painted) == 5, "width sees painted text only")


# --- adversarial edges --------------------------------------------------------


def test_paint_handles_empty_text() raises:
    _assert(
        Style().foreground(Color.RED).paint("") == "\x1b[31m\x1b[0m",
        "empty text still opens and resets",
    )
    _assert(Style().paint("") == "", "empty style with empty text")


def test_strip_escapes_consumes_unterminated_sequences() raises:
    _assert(strip_escapes("\x1b[31") == "", "unterminated CSI consumes to end")
    _assert(
        strip_escapes("a\x1b]8;;link") == "a",
        "unterminated OSC consumes to end",
    )
    _assert(strip_escapes("a\x1b(") == "a", "unterminated charset shift")
    _assert(visible_width("\x1b[31") == 0, "unterminated CSI is invisible")


def test_strip_escapes_aborted_sequences_keep_following_text() raises:
    # A broken CSI aborted by a foreign byte must never swallow the text
    # after it — the terminal starts over at the aborting byte (ECMA-48).
    _assert(
        strip_escapes("\x1b[31\x1b[0mAfter") == "After",
        "a new ESC aborts a broken CSI; the next sequence still strips",
    )
    _assert(
        strip_escapes("\x1b[31\nrest") == "\nrest",
        "a newline aborts a broken CSI and stays visible",
    )
    _assert(
        visible_width("\x1b[31\x1b[0mAfter") == 5,
        "text after an aborted CSI is visible",
    )
    _assert(
        strip_escapes("\x1b(\x1b[32mOK") == "OK",
        "a new ESC aborts a broken plain sequence too",
    )


def test_strip_escapes_osc_interrupted_by_new_sequence() raises:
    _assert(
        strip_escapes("\x1b]0;title\x1b[31mred") == "red",
        "an inner CSI ends the OSC scan and is parsed itself",
    )


def test_strip_escapes_removes_string_commands() raises:
    # DCS, SOS, PM, APC (ECMA-48 §5.6): the payload runs to ST and never
    # reaches the reader — a terminal consumes the whole command string.
    _assert(
        strip_escapes("\x1bPq#0;1;0;0\x1b\\after") == "after",
        "DCS payload is consumed to ST",
    )
    _assert(
        strip_escapes("\x1bXhidden\x1b\\after") == "after",
        "SOS payload is consumed to ST",
    )
    _assert(
        strip_escapes("\x1b^hidden\x1b\\after") == "after",
        "PM payload is consumed to ST",
    )
    _assert(
        strip_escapes("\x1b_hidden\x1b\\after") == "after",
        "APC payload is consumed to ST",
    )
    _assert(
        visible_width("\x1bPq#0;1;0;0\x1b\\after") == 5,
        "DCS payload has no width",
    )


def test_strip_escapes_string_command_bel_is_payload() raises:
    # BEL terminates OSC (xterm practice) but is data inside the others.
    _assert(
        strip_escapes("\x1bPdata\x07more\x1b\\after") == "after",
        "BEL does not terminate a DCS string",
    )
    _assert(
        strip_escapes("\x1b]0;title\x07after") == "after",
        "BEL still terminates OSC",
    )


def test_strip_escapes_string_command_edges() raises:
    _assert(
        strip_escapes("a\x1bPlost") == "a",
        "unterminated DCS consumes to end",
    )
    _assert(
        strip_escapes("\x1bXdata\x1b[31mred\x1b[0m") == "red",
        "an inner CSI ends the string scan and is parsed itself",
    )


def test_from_hex_rejects_multibyte_six_byte_input() raises:
    var rejected = 0
    try:
        _ = Color.from_hex("ééé")  # six bytes, zero hex digits
    except error:
        rejected += 1
        _assert(String(error).find("color.Color") >= 0, "error names module")
    _assert(rejected == 1, "multi-byte input rejected, no crash")


# --- public surface ----------------------------------------------------------


def test_public_package_surface_resolves() raises:
    _assert(
        PublicPainter.plain().red("x") == "x",
        "Painter re-exported from the package root",
    )
    _assert(
        public_strip_escapes("\x1b[31mx\x1b[0m") == "x",
        "strip_escapes re-exported from the package root",
    )


# --- runner ------------------------------------------------------------------


def main() raises:
    print("color-mojo tests")
    var failures = 0

    try:
        test_sgr_attribute_codes_skip_six()
        print("  PASS test_sgr_attribute_codes_skip_six")
    except error:
        print("  FAIL test_sgr_attribute_codes_skip_six:", String(error))
        failures += 1

    try:
        test_sgr_byte_classes_match_ecma48()
        print("  PASS test_sgr_byte_classes_match_ecma48")
    except error:
        print("  FAIL test_sgr_byte_classes_match_ecma48:", String(error))
        failures += 1

    try:
        test_write_decimal_fills_exactly()
        print("  PASS test_write_decimal_fills_exactly")
    except error:
        print("  FAIL test_write_decimal_fills_exactly:", String(error))
        failures += 1

    try:
        test_digit_pairs_spot_checks()
        print("  PASS test_digit_pairs_spot_checks")
    except error:
        print("  FAIL test_digit_pairs_spot_checks:", String(error))
        failures += 1

    try:
        test_rgb_to_ansi256_reference_vectors()
        print("  PASS test_rgb_to_ansi256_reference_vectors")
    except error:
        print("  FAIL test_rgb_to_ansi256_reference_vectors:", String(error))
        failures += 1

    try:
        test_ansi256_to_named16_reference_vectors()
        print("  PASS test_ansi256_to_named16_reference_vectors")
    except error:
        print(
            "  FAIL test_ansi256_to_named16_reference_vectors:", String(error)
        )
        failures += 1

    try:
        test_color_level_ordering()
        print("  PASS test_color_level_ordering")
    except error:
        print("  FAIL test_color_level_ordering:", String(error))
        failures += 1

    try:
        test_resolve_no_color_always_wins()
        print("  PASS test_resolve_no_color_always_wins")
    except error:
        print("  FAIL test_resolve_no_color_always_wins:", String(error))
        failures += 1

    try:
        test_resolve_tty_gate()
        print("  PASS test_resolve_tty_gate")
    except error:
        print("  FAIL test_resolve_tty_gate:", String(error))
        failures += 1

    try:
        test_resolve_forced_ladder()
        print("  PASS test_resolve_forced_ladder")
    except error:
        print("  FAIL test_resolve_forced_ladder:", String(error))
        failures += 1

    try:
        test_resolve_zero_never_forces()
        print("  PASS test_resolve_zero_never_forces")
    except error:
        print("  FAIL test_resolve_zero_never_forces:", String(error))
        failures += 1

    try:
        test_resolve_dumb_outranks_colorterm()
        print("  PASS test_resolve_dumb_outranks_colorterm")
    except error:
        print("  FAIL test_resolve_dumb_outranks_colorterm:", String(error))
        failures += 1

    try:
        test_resolve_clicolor_zero_disables()
        print("  PASS test_resolve_clicolor_zero_disables")
    except error:
        print("  FAIL test_resolve_clicolor_zero_disables:", String(error))
        failures += 1

    try:
        test_resolve_force_color_false_disables()
        print("  PASS test_resolve_force_color_false_disables")
    except error:
        print("  FAIL test_resolve_force_color_false_disables:", String(error))
        failures += 1

    try:
        test_resolve_force_color_numeric_floors()
        print("  PASS test_resolve_force_color_numeric_floors")
    except error:
        print("  FAIL test_resolve_force_color_numeric_floors:", String(error))
        failures += 1

    try:
        test_attribute_bits_are_distinct()
        print("  PASS test_attribute_bits_are_distinct")
    except error:
        print("  FAIL test_attribute_bits_are_distinct:", String(error))
        failures += 1

    try:
        test_attribute_combination()
        print("  PASS test_attribute_combination")
    except error:
        print("  FAIL test_attribute_combination:", String(error))
        failures += 1

    try:
        test_color_constants_store_palette_indexes()
        print("  PASS test_color_constants_store_palette_indexes")
    except error:
        print(
            "  FAIL test_color_constants_store_palette_indexes:", String(error)
        )
        failures += 1

    try:
        test_color_value_equality()
        print("  PASS test_color_value_equality")
    except error:
        print("  FAIL test_color_value_equality:", String(error))
        failures += 1

    try:
        test_color_from_hex_parses_forms()
        print("  PASS test_color_from_hex_parses_forms")
    except error:
        print("  FAIL test_color_from_hex_parses_forms:", String(error))
        failures += 1

    try:
        test_color_from_hex_rejects_malformed()
        print("  PASS test_color_from_hex_rejects_malformed")
    except error:
        print("  FAIL test_color_from_hex_rejects_malformed:", String(error))
        failures += 1

    try:
        test_color_downgrade_walks_the_ladder()
        print("  PASS test_color_downgrade_walks_the_ladder")
    except error:
        print("  FAIL test_color_downgrade_walks_the_ladder:", String(error))
        failures += 1

    try:
        test_style_empty_is_identity()
        print("  PASS test_style_empty_is_identity")
    except error:
        print("  FAIL test_style_empty_is_identity:", String(error))
        failures += 1

    try:
        test_style_paints_named_colors()
        print("  PASS test_style_paints_named_colors")
    except error:
        print("  FAIL test_style_paints_named_colors:", String(error))
        failures += 1

    try:
        test_style_paints_attributes()
        print("  PASS test_style_paints_attributes")
    except error:
        print("  FAIL test_style_paints_attributes:", String(error))
        failures += 1

    try:
        test_style_paints_combined_parameters()
        print("  PASS test_style_paints_combined_parameters")
    except error:
        print("  FAIL test_style_paints_combined_parameters:", String(error))
        failures += 1

    try:
        test_style_paints_extended_colors()
        print("  PASS test_style_paints_extended_colors")
    except error:
        print("  FAIL test_style_paints_extended_colors:", String(error))
        failures += 1

    try:
        test_style_paint_into_matches_paint()
        print("  PASS test_style_paint_into_matches_paint")
    except error:
        print("  FAIL test_style_paint_into_matches_paint:", String(error))
        failures += 1

    try:
        test_painter_from_level_is_deterministic()
        print("  PASS test_painter_from_level_is_deterministic")
    except error:
        print("  FAIL test_painter_from_level_is_deterministic:", String(error))
        failures += 1

    try:
        test_painter_plain_never_escapes()
        print("  PASS test_painter_plain_never_escapes")
    except error:
        print("  FAIL test_painter_plain_never_escapes:", String(error))
        failures += 1

    try:
        test_painter_downgrades_through_paint()
        print("  PASS test_painter_downgrades_through_paint")
    except error:
        print("  FAIL test_painter_downgrades_through_paint:", String(error))
        failures += 1

    try:
        test_painter_paint_into_matches_paint()
        print("  PASS test_painter_paint_into_matches_paint")
    except error:
        print("  FAIL test_painter_paint_into_matches_paint:", String(error))
        failures += 1

    try:
        test_painter_composes_with_resolve()
        print("  PASS test_painter_composes_with_resolve")
    except error:
        print(
            "  FAIL test_painter_composes_with_resolve:",
            String(error),
        )
        failures += 1

    try:
        test_strip_escapes_removes_csi()
        print("  PASS test_strip_escapes_removes_csi")
    except error:
        print("  FAIL test_strip_escapes_removes_csi:", String(error))
        failures += 1

    try:
        test_strip_escapes_removes_osc_hyperlinks()
        print("  PASS test_strip_escapes_removes_osc_hyperlinks")
    except error:
        print(
            "  FAIL test_strip_escapes_removes_osc_hyperlinks:", String(error)
        )
        failures += 1

    try:
        test_strip_escapes_removes_plain_escape_sequences()
        print("  PASS test_strip_escapes_removes_plain_escape_sequences")
    except error:
        print(
            "  FAIL test_strip_escapes_removes_plain_escape_sequences:",
            String(error),
        )
        failures += 1

    try:
        test_strip_escapes_is_terminal_accurate_for_bare_escape()
        print("  PASS test_strip_escapes_is_terminal_accurate_for_bare_escape")
    except error:
        print(
            "  FAIL test_strip_escapes_is_terminal_accurate_for_bare_escape:",
            String(error),
        )
        failures += 1

    try:
        test_visible_width_counts_code_points()
        print("  PASS test_visible_width_counts_code_points")
    except error:
        print("  FAIL test_visible_width_counts_code_points:", String(error))
        failures += 1

    try:
        test_visible_tools_agree_with_paint()
        print("  PASS test_visible_tools_agree_with_paint")
    except error:
        print("  FAIL test_visible_tools_agree_with_paint:", String(error))
        failures += 1

    try:
        test_public_package_surface_resolves()
        print("  PASS test_public_package_surface_resolves")
    except error:
        print("  FAIL test_public_package_surface_resolves:", String(error))
        failures += 1

    try:
        test_paint_handles_empty_text()
        print("  PASS test_paint_handles_empty_text")
    except error:
        print("  FAIL test_paint_handles_empty_text:", String(error))
        failures += 1

    try:
        test_strip_escapes_consumes_unterminated_sequences()
        print("  PASS test_strip_escapes_consumes_unterminated_sequences")
    except error:
        print(
            "  FAIL test_strip_escapes_consumes_unterminated_sequences:",
            String(error),
        )
        failures += 1

    try:
        test_strip_escapes_aborted_sequences_keep_following_text()
        print("  PASS test_strip_escapes_aborted_sequences_keep_following_text")
    except error:
        print(
            "  FAIL test_strip_escapes_aborted_sequences_keep_following_text:",
            String(error),
        )
        failures += 1

    try:
        test_strip_escapes_osc_interrupted_by_new_sequence()
        print("  PASS test_strip_escapes_osc_interrupted_by_new_sequence")
    except error:
        print(
            "  FAIL test_strip_escapes_osc_interrupted_by_new_sequence:",
            String(error),
        )
        failures += 1

    try:
        test_strip_escapes_removes_string_commands()
        print("  PASS test_strip_escapes_removes_string_commands")
    except error:
        print(
            "  FAIL test_strip_escapes_removes_string_commands:", String(error)
        )
        failures += 1

    try:
        test_strip_escapes_string_command_bel_is_payload()
        print("  PASS test_strip_escapes_string_command_bel_is_payload")
    except error:
        print(
            "  FAIL test_strip_escapes_string_command_bel_is_payload:",
            String(error),
        )
        failures += 1

    try:
        test_strip_escapes_string_command_edges()
        print("  PASS test_strip_escapes_string_command_edges")
    except error:
        print("  FAIL test_strip_escapes_string_command_edges:", String(error))
        failures += 1

    try:
        test_from_hex_rejects_multibyte_six_byte_input()
        print("  PASS test_from_hex_rejects_multibyte_six_byte_input")
    except error:
        print(
            "  FAIL test_from_hex_rejects_multibyte_six_byte_input:",
            String(error),
        )
        failures += 1

    if failures == 0:
        print("all tests passed")
    else:
        print(String(failures) + " test(s) failed")
        raise Error("test failures")
